apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpd
  namespace: httpd
spec:
  gateways:
  - httpd-gateway
  hosts:
  - httpd-istio-system.apps.cluster-750e.sandbox1320.opentlc.com
  http:
  - match:
    - uri:
        exact: /index.html
    route:
    - destination:
        host: httpd
        port:
          number: 8080
